-- migrate:up
CREATE TABLE history (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    world_id integer NOT NULL,
    item_id integer NOT NULL,
    quantity integer NOT NULL,
    unit_price integer NOT NULL,
    buyer varchar(100) NOT NULL,
    purchased_on timestamptz NOT NULL,
    CONSTRAINT pk_history PRIMARY KEY (id),
    CONSTRAINT fk_listing_world FOREIGN KEY (world_id) REFERENCES world (id),
    CONSTRAINT fk_listing_item FOREIGN KEY (item_id) REFERENCES item (id)
);

-- migrate:down

