-- migrate:up
CREATE TABLE character (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    world_id integer NOT NULL,
    lodestone integer NOT NULL,
    CONSTRAINT pk_character PRIMARY KEY (id),
    CONSTRAINT fk_character_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_character_world FOREIGN KEY (world_id) REFERENCES world (id),
    CONSTRAINT uq_character_user_world UNIQUE (user_id, world_id)
);

-- migrate:down

