-- migrate:up
CREATE TABLE listing (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    world_id integer NOT NULL,
    retainer_id integer NOT NULL,
    item_id integer NOT NULL,
    quantity integer NOT NULL,
    unit_price integer NOT NULL,
    is_hq boolean NOT NULL DEFAULT FALSE,
    is_mannequin boolean NOT NULL DEFAULT FALSE,
    updated_on timestamptz NOT NULL,
    CONSTRAINT pk_listing PRIMARY KEY (id),
    CONSTRAINT fk_listing_world FOREIGN KEY (world_id) REFERENCES world (id),
    CONSTRAINT fk_listing_retainer FOREIGN KEY (retainer_id) REFERENCES retainer (id),
    CONSTRAINT fk_listing_item FOREIGN KEY (item_id) REFERENCES item (id)
);

-- migrate:down

