-- migrate:up
INSERT INTO job (id, name, abbreviation)
VALUES (0, 'Adventurer', null),
       (1, 'Gladiator', 'GLA'),
       (2, 'Pugilist', 'PGL'),
       (3, 'Marauder', 'MRD'),
       (4, 'Lancer', 'LNC'),
       (5, 'Archer', 'ARC'),
       (6, 'Conjurer', 'CNJ'),
       (7, 'Thaumaturge', 'THM'),
       (8, 'Carpenter', 'CRP'),
       (9, 'Blacksmith', 'BSM'),
       (10, 'Armorer', 'ARM'),
       (11, 'Goldsmith', 'GSM'),
       (12, 'Leatherworker', 'LTW'),
       (13, 'Weaver', 'WVR'),
       (14, 'Alchemist', 'ALC'),
       (15, 'Culinarian', 'CUL'),
       (16, 'Miner', 'MIN'),
       (17, 'Botanist', 'BTN'),
       (18, 'Fisher', 'FSH'),
       (19, 'Paladin', 'PLD'),
       (20, 'Monk', 'MNK'),
       (21, 'Warrior', 'WAR'),
       (22, 'Dragoon', 'DRG'),
       (23, 'Bard', 'BRD'),
       (24, 'White Mage', 'WHM'),
       (25, 'Black Mage', 'BLM'),
       (26, 'Arcanist', 'ACN'),
       (27, 'Summoner', 'SMN'),
       (28, 'Scholar', 'SCH'),
       (29, 'Rogue', 'ROG'),
       (30, 'Ninja', 'NIN'),
       (31, 'Machinist', 'MCH'),
       (32, 'Dark Knight', 'DRK'),
       (33, 'Astrologian', 'AST'),
       (34, 'Samurai', 'SAM'),
       (35, 'Red Mage', 'RDM'),
       (36, 'Blue Mage', 'BLU'),
       (37, 'Gunbreaker', 'GNB'),
       (38, 'Dancer', 'DNC'),
       (39, 'Reaper', 'RPR'),
       (40, 'Sage', 'SGE'),
       (41, 'Viper', 'VPR'),
       (42, 'Pictomancer', 'PCT');


-- migrate:down

