-- migrate:up
CREATE TABLE datacenter (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    region_id integer NOT NULL,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_datacenter PRIMARY KEY (id),
    CONSTRAINT fk_datacenter_region FOREIGN KEY (region_id) REFERENCES region (id)
);

-- migrate:down

