-- migrate:up
CREATE TABLE tax_rate (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    world_id integer NOT NULL,
    city_id integer NOT NULL,
    tax_rate integer NOT NULL,
    updated_on timestamptz NOT NULL,
    CONSTRAINT pk_tax_rate PRIMARY KEY (id),
    CONSTRAINT fk_tax_rate_world FOREIGN KEY (world_id) REFERENCES world (id),
    CONSTRAINT fk_tax_rate_city FOREIGN KEY (city_id) REFERENCES city (id),
    CONSTRAINT uq_tax_rate UNIQUE (world_id, city_id)
);

-- migrate:down

