-- migrate:up
CREATE TABLE retainer (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    world_id integer NOT NULL,
    city_id integer NOT NULL,
    character_id integer NULL,
    name varchar (50) NOT NULL,
    CONSTRAINT pk_retainer PRIMARY KEY (id),
    CONSTRAINT fk_retainer_world FOREIGN KEY (world_id) REFERENCES world (id),
    CONSTRAINT fk_retainer_city FOREIGN KEY (city_id) REFERENCES city (id),
    CONSTRAINT fk_retainer_character FOREIGN KEY (character_id) REFERENCES character (id),
    CONSTRAINT uq_retainer_world_name UNIQUE (world_id, name)
);

-- migrate:down

