services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  queue:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
      - "15692:15692"   # Prometheus
    volumes:
      - queue_data:/var/lib/rabbitmq

  dbmate:
    image: ghcr.io/amacneil/dbmate
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    volumes:
      - ./deploy/db/migrations:/db/migrations
      - ./deploy/scripts/migrate-wait.sh:/migrate-wait.sh
    entrypoint: ["/migrate-wait.sh"]  # Waits for Postgres before running required migrations

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3030:3030"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  queue_data:
  grafana_data: